version: '3.4'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "CardCli"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=CardCli;User=root;Password=123456
  frontend:
    build:
      context: ./ProCardCli-front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  my-db:
